_wandb:
    value:
        cli_version: 0.22.0
        e:
            xz5vm7fva4h06mmndmx5qqq6w8qv0b73:
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "122143162368"
                        used: "85531549696"
                email: emmanuel.cruzd@alumno.buap.mx
                executable: /usr/bin/python3
                git:
                    commit: a7af8ff6f2750259123a7d85e46aed3f0fe9c544
                    remote: https://github.com/emmdaz/Plant-Pathology-Classificator.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-e211b3b7-2fe1-5939-cf8d-3f4e34d9ad5d
                host: fd3373bd4a55
                memory:
                    total: "16598601728"
                os: Linux-6.14.0-34-generic-x86_64-with-glibc2.29
                program: Plant-Pathology-Classificator/Trials/Plant-Pathology-Classificator-Conv2D-Residual-Trials.ipynb
                python: CPython 3.8.10
                root: /tf/Plant-Pathology-Classificator/Trials
                startedAt: "2025-11-06T22:02:48.102488Z"
                writerId: xz5vm7fva4h06mmndmx5qqq6w8qv0b73
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
            - "2": batch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.8.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
            "3":
                - 7
                - 13
                - 16
                - 38
            "4": 3.8.10
            "5": 0.22.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.0
            "13": linux-x86_64
activations_per_layer:
    value:
        - selu
        - leaky_relu
        - relu6
        - selu
        - relu6
        - relu
        - relu6
        - relu6
        - leaky_relu
        - leaky_relu
        - leaky_relu
        - relu6
        - relu
        - selu
        - relu
        - relu6
        - relu6
        - leaky_relu
        - relu6
        - relu6
        - relu6
        - relu6
        - relu6
        - relu6
        - relu6
        - relu6
dropout_per_layer:
    value:
        - "n"
        - "y"
        - "y"
        - "n"
        - "n"
        - "y"
        - "y"
        - "n"
        - "y"
        - "n"
        - "y"
        - "y"
        - "y"
        - "y"
        - "n"
        - "y"
        - "n"
        - "y"
        - "y"
        - "y"
        - "y"
        - "n"
        - "n"
        - "n"
        - "n"
dropout_percentage_per_layer:
    value:
        - 0
        - 0.3047285581907521
        - 0.49703800493735983
        - 0
        - 0
        - 0.48583702669385936
        - 0.41216039180606767
        - 0
        - 0.40319598227675935
        - 0
        - 0.23498545671602156
        - 0.3808093926744378
        - 0.4488273611853684
        - 0.444675920639849
        - 0
        - 0.4566983262589644
        - 0
        - 0.2087779420784776
        - 0.34846301966712206
        - 0.40842639695626226
        - 0.30983826799174413
        - 0
        - 0
        - 0
        - 0
kernel_per_layer:
    value:
        - 74
        - 53
        - 41
        - 128
        - 86
        - 120
        - 100
        - 123
        - 88
        - 76
        - 50
        - 25
        - 107
        - 87
        - 45
        - 18
        - 42
        - 74
        - 117
        - 13
        - 26
        - 16
        - 118
        - 89
        - 58
        - 18
kernel_size_per_layer:
    value:
        - 3
        - 3
        - 7
        - 3
        - 10
        - 7
        - 7
        - 8
        - 8
        - 3
        - 7
        - 3
        - 8
        - 10
        - 3
        - 3
        - 8
        - 7
        - 3
        - 7
        - 10
        - 10
        - 10
        - 7
        - 8
        - 3
learning_rate:
    value: 0.0023305466173599446
n_layers:
    value: 25
optimizer:
    value: sgd
r_value:
    value: 3.7045539144082377e-06
r_value2:
    value: 7.844008800205617e-06
regularizer:
    value: L2
