_wandb:
    value:
        cli_version: 0.22.0
        e:
            hxsmgftc53cty3wpa7c7546y0pi6suog:
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "122143162368"
                        used: "85534461952"
                email: emmanuel.cruzd@alumno.buap.mx
                executable: /usr/bin/python3
                git:
                    commit: a7af8ff6f2750259123a7d85e46aed3f0fe9c544
                    remote: https://github.com/emmdaz/Plant-Pathology-Classificator.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-e211b3b7-2fe1-5939-cf8d-3f4e34d9ad5d
                host: fd3373bd4a55
                memory:
                    total: "16598601728"
                os: Linux-6.14.0-34-generic-x86_64-with-glibc2.29
                program: Plant-Pathology-Classificator/Trials/Plant-Pathology-Classificator-Conv2D-Residual-Trials.ipynb
                python: CPython 3.8.10
                root: /tf/Plant-Pathology-Classificator/Trials
                startedAt: "2025-11-06T22:07:37.973333Z"
                writerId: hxsmgftc53cty3wpa7c7546y0pi6suog
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
            - "2": batch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.8.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
            "3":
                - 7
                - 13
                - 16
                - 38
            "4": 3.8.10
            "5": 0.22.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.0
            "13": linux-x86_64
activations_per_layer:
    value:
        - relu
        - selu
        - relu6
        - selu
        - relu6
        - relu6
        - relu6
        - relu6
        - leaky_relu
        - relu6
        - relu6
        - leaky_relu
        - relu6
        - leaky_relu
        - relu
        - leaky_relu
        - leaky_relu
        - relu6
dropout_per_layer:
    value:
        - "y"
        - "y"
        - "y"
        - "y"
        - "y"
        - "y"
        - "n"
        - "y"
        - "n"
        - "n"
        - "y"
        - "y"
        - "y"
        - "y"
        - "n"
        - "y"
        - "y"
dropout_percentage_per_layer:
    value:
        - 0.4786577245139433
        - 0.24219035714929957
        - 0.3371032867702021
        - 0.36406807597414564
        - 0.27800342070079387
        - 0.20550317886368896
        - 0
        - 0.4542699708783568
        - 0
        - 0
        - 0.2703085343557729
        - 0.3426605122294132
        - 0.479877291874947
        - 0.31863695701886463
        - 0
        - 0.23654395056297173
        - 0.35815675010448317
kernel_per_layer:
    value:
        - 38
        - 55
        - 25
        - 49
        - 30
        - 31
        - 13
        - 50
        - 23
        - 45
        - 54
        - 35
        - 64
        - 12
        - 31
        - 41
        - 53
        - 24
kernel_size_per_layer:
    value:
        - 10
        - 8
        - 10
        - 10
        - 8
        - 3
        - 8
        - 8
        - 10
        - 7
        - 8
        - 3
        - 7
        - 10
        - 7
        - 3
        - 8
        - 3
learning_rate:
    value: 0.00012066542594676561
n_layers:
    value: 17
optimizer:
    value: rmsprop
r_value:
    value: 6.593945821057664e-05
r_value2:
    value: 6.26702780441174e-05
regularizer:
    value: L1
